# FROM freqtradeorg/freqtrade:develop
FROM freqtradeorg/freqtrade:develop_plot

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
# USER root

# The below dependency - pyti - serves as an example. Please use whatever you need!
RUN pip install --user pyti

# Switch back to user (only if you required root above)
# USER ftuser

# Install the 'ta' package using pip
RUN pip install ta
